services:
  api:
    build:
      context: ./ReviewApp-server
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./ReviewApp-server/.env
    volumes:
      - ./ReviewApp-server:/app
      - /app/node_modules
    networks:
      - nestjs-expo-app
    ports:
      - 4000:4000

  expo:
    build:
      context: ./ReviewApp
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./ReviewApp/.env
    volumes:
      - ./ReviewApp:/app
      - /app/node_modules
    networks:
      - nestjs-expo-app
    ports:
      - 8081:8081
    depends_on:
      - api

networks:
  nestjs-expo-app:
    driver: bridge
