
POST http://localhost:4000/comments
Content-Type: application/json

{
  "text": "This is a comment on the review eero.",
  "id_user": 1,
  "id_review": 1
}
### reply (parentId)
POST http://localhost:4000/comments/reply/2
Content-Type: application/json

{
    "text": "Reply reply",
    "id_review": 1,
    "id_user": 1
}

### Get replies of parent comment!
GET http://localhost:4000/comments/reply/1


### delete
DELETE http://localhost:4000/comments/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkplZSIsInN1YiI6NCwicm9sZSI6InVzZXIiLCJ1c2VybmFtZSI6IkplZSIsImlhdCI6MTczNDYxOTk4MSwiZXhwIjoxNzM0NjIzNTgxfQ.j2cnHC0fIHusp16OLUC4nnbKU6_FetxCwcQ1ngYUnYA

### get all comments
GET http://localhost:4000/comments/

###

GET http://localhost:4000/comments/review/1


### Get all reviews
GET http://localhost:4000/review