### Create a new review
POST http://localhost:3000/review
Content-Type: application/json

{
    "reviewname": "es",
    "reviewRating": 4,
    "reviewDescription": "hyvää",
    "category": "x",
    "imageUrl": "http://example.com/image.jpg",
    "id_user": 1
}

### Create a new user
POST  http://localhost:3000/users/register
Content-Type: application/json

{
    "password": "S",
    "email": "S",
    "username": "Eero"
}

### Get all reviews
GET http://localhost:3000/review

### Get all reviews
GET http://localhost:3000/review/all?category=softdrink

### Get one dood reviews
GET http://localhost:3000/review/user/1

### Get a single review by ID
GET http://localhost:3000/review/6

###
GET http://localhost:3000/users/4

### Update Review Request
PUT http://localhost:3000/review
Content-Type: application/json

{
  "id_review": 3,
  "id_user": 1,
  "reviewname": "Updated revieww",
  "reviewRating": 5,
  "imageUrl": "http://image.url"
}

### Delete a review
DELETE http://localhost:3000/review/67
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkUiLCJzdWIiOjEsInJvbGUiOiJ1c2VyIiwidXNlcm5hbWUiOiJFIiwiaWF0IjoxNzMxODQwOTQ3LCJleHAiOjE3MzE4NzY5NDd9.V4oE7kgtPlKCaMr8eQnF2iCAtNUXGfhEGp8e_arZFFU

###Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "E",
    "password": "E"
}

### Get with category using id
GET http://localhost:3000/review/users/1/reviews?category=softdrink






