### Create a new review
POST http://localhost:3000/review
Content-Type: application/json

{
    "reviewname": "es",
    "reviewRating": 4,
    "reviewDescription": "hyvää",
    "category": "x",
    "imageUrl": "http://example.com/image.jpg",
    "id_user": 1
}

### Create a new user
POST  https://reviewapp-d7gtbubkavccggah.germanywestcentral-01.azurewebsites.net/users/register
Content-Type: application/json

{
    "password": "S",
    "email": "something@something.com",
    "username": "Eero"
}

### Get all reviews
GET http://localhost:4000/review

### Get all reviews
GET http://localhost:4000/review/all?category=hotbeverage

### Get user reviews with category
GET http://localhost:4000/review/1?category=softdrink

### Get one dood reviews
GET http://localhost:4000/review/user/1

### Get a single review by ID
GET http://localhost:4000/review/28

###
GET http://localhost:3000/users/1

### Update Review Request
PUT http://localhost:4000/review
Content-Type: application/json

{
  "id_review": 9,
  "id_user": 1,
  "reviewname": "Updated revieww",
  "reviewRating": 5,
  "imageUrl": "http://image.url"
}

### Delete a review
DELETE http://localhost:4000/review/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IkUiLCJzdWIiOjEsInJvbGUiOiJ1c2VyIiwidXNlcm5hbWUiOiJFIiwiaWF0IjoxNzMxODQwOTQ3LCJleHAiOjE3MzE4NzY5NDd9.V4oE7kgtPlKCaMr8eQnF2iCAtNUXGfhEGp8e_arZFFU

###Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "E",
    "password": "E"
}

### Get with category using id
GET http://localhost:3000/review/users/1/reviews?category=softdrink


### Test for Recommending Reviews
GET http://localhost:3000/review/recommend?userReview=Very good

###
GET http://localhost:4000/review/user/favorites/1


