POST http://localhost:3000/replies
Content-Type: application/json

{
  "text": "This is a reply",
  "id_comment": 3,
  "id_user": 3
}


### get all replies
GET http://localhost:3000/replies

### get by id
GET http://localhost:3000/replies/comment/3

###
GET http://localhost:3000/review