### Create a new user
POST  http://localhost:4000/auth/register
Content-Type: application/json

{
    "password": "S",
    "email": "eero.kantonen11@gmail.com",
    "username": "Eero Kantonen",
    "role": "admin"
}

### Find User
GET http://localhost:4000/users/1

### Find UserStats
GET http://localhost:4000/users/stats/1


###Login
POST http://localhost:4000/auth/login
Content-Type: application/json

{
    "email": "SSS",
    "password": "SSS"
}
### Update avatar
PATCH http://localhost:4000/users/avatar/4
Content-Type: application/json

{
  "avatar": "https://cdn.pixabay.com/photo/201e5/10/05/22/37/blank-profile-picture-973460_1280.png"
}
