### Create a new user
POST  http://localhost:4000/users/register
Content-Type: application/json

{
    "password": "S",
    "email": "eero.kantonen11@gmail.com",
    "username": "Eero Kantonen",
    "role": "admin"
}

### Find User
GET http://localhost:4000/users/1

### Find Users
GET http://localhost:4000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IlNTUyIsInN1YiI6Miwicm9sZSI6InVzZXIiLCJ1c2VybmFtZSI6IlNTUyIsImF2YXRhciI6Imh0dHBzOi8vY2RuLnBpeGFiYXkuY29tL3Bob3RvLzIwMTUvMTAvMDUvMjIvMzcvYmxhbmstcHJvZmlsZS1waWN0dXJlLTk3MzQ2MF8xMjgwLnBuZyIsImlhdCI6MTc0ODg3NTE1MCwiZXhwIjoxNzQ4ODc4NzUwfQ.uzpoYxR9Yf07iSIQuHYRtusaEUZp3tu-HiC7JH3U-Gg

###Login
POST http://localhost:4000/auth/login
Content-Type: application/json

{
    "email": "SSS",
    "password": "SSS"
}
### Update avatar
PATCH http://localhost:4000/users/12/avatar
Content-Type: application/json

{
  "avatar": "https://cdn.pixabay.com/photo/201e5/10/05/22/37/blank-profile-picture-973460_1280.png"
}
