name: Expo Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: List contents of front-end directory
        run: ls -la front-end  

      - name: Install dependencies (Frontend)
        run: cd front-end && npm install  

      - name: Install Expo CLI
        run: npm install -g expo-cli

      - name: Run Expo for Android
        run: cd front-end && npm run android --non-interactive

      - name: Run Expo for iOS
        run: cd front-end && npm run ios --non-interactive
